defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: 2

development:
  <<: *defaults
  database: inventory

test: 
  <<: *defaults
  database: inventory_test